### ISSUE TITLE
Bootstrap or Foundation or both?

### ISSUE THREAD

**Issue by AnBauer** [leanovate/generator-cc-angular#1]
While working on it, I asked myself the question if I should to stick to bootstrap or switch to Foundation or have both and leave it up to the user. If anyone really uses this it would be nice to have some feedback.

Thx
André

**Comment by jaroslavrehorka** [comment]
I personaly use bootstrap - because of tons of plugins, huge amount of people using it and angular team. I had a quick look at foundation directives yesterday but at the moment ui-bootstrap is my choice.
